//
//  TaskPresets.swift
//
// Copyright 2023  OpenAlloc LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//

import Collections
import Foundation

public typealias TaskPresetDict = OrderedDictionary<TaskGroup, [TaskPreset]>

// see README for guidelines on adding/maintaining these presets.
public let taskPresets: TaskPresetDict = [
    .travelDocumentation: [
        TaskPreset("Banking Contact List"),
        TaskPreset("Cash", [FieldPreset("Amount", unitsSuffix: "$", initialValue: Int16(500), upperBound: Int16(10000))]),
        TaskPreset("Credit/ATM cards", [FieldPreset("Count", initialValue: Int16(2), upperBound: Int16(20))]),
        TaskPreset("Emergency Contact List"),
        TaskPreset("Government ID"),
        TaskPreset("Hand Sanitizer"),
        TaskPreset("Insurance Cards"),
        TaskPreset("Itinerary (printed)"),
        TaskPreset("Medication List"),
        TaskPreset("Passport (original)"),
        TaskPreset("Passport (printed copy)"),
        TaskPreset("Tickets/Passes"),
        TaskPreset("Visa/Embassy Info"),
    ],
    .travelToiletries: [
        TaskPreset("Bandages"),
        TaskPreset("Dental Floss"),
        TaskPreset("Deodorant"),
        TaskPreset("First-Aid Ointment"),
        TaskPreset("Hand Sanitizer"),
        TaskPreset("Lip Balm"),
        TaskPreset("Medications"),
        TaskPreset("Moisturizer"),
        TaskPreset("Nail Clippers"),
        TaskPreset("Pain Relievers"),
        TaskPreset("Personal Hygiene"),
        TaskPreset("Shaving"),
        TaskPreset("Soap"),
        TaskPreset("Sunscreen"),
        TaskPreset("Toothbrush"),
        TaskPreset("Toothpaste"),
        TaskPreset("Tweezers"),
    ],
    .travelAccessories: [
        TaskPreset("Books or E-Books"),
        TaskPreset("Camera/Lenses"),
        TaskPreset("Cell Phone"),
        TaskPreset("Change of Clothes"),
        TaskPreset("Disinfecting Wipes"),
        TaskPreset("Earplugs"),
        TaskPreset("Electronic Chargers"),
        TaskPreset("Empty Water Bottle"),
        TaskPreset("Eyeglasses"),
        TaskPreset("Eye Mask"),
        TaskPreset("Face Masks"),
        TaskPreset("Facial Tissues"),
        TaskPreset("Headphones"),
        TaskPreset("House/Car Keys"),
        TaskPreset("Laptop/Tablet/E-Reader"),
        TaskPreset("Language Translator"),
        TaskPreset("Laundry Kit"),
        TaskPreset("Maps/Guidebooks"),
        TaskPreset("Pen/Marker"),
        TaskPreset("Plug Adapter"),
        TaskPreset("Snacks"),
        TaskPreset("Sunglasses"),
        TaskPreset("Thumbdrive/Memory Card"),
        TaskPreset("Travel Blanket"),
        TaskPreset("Travel Pillow"),
        TaskPreset("Collapsible Tote"),
        TaskPreset("Waist storage pack"),
        TaskPreset("Wallet (decoy)"),
    ],
    .travelClothing: [
        TaskPreset("Belts"),
        TaskPreset("Casual Pants", [FieldPreset("Pair Count", unitsSuffix: "pr", initialValue: Int16(2), upperBound: Int16(20))]),
        TaskPreset("Casual Shirts", [FieldPreset("Count", initialValue: Int16(5), upperBound: Int16(20))]),
        TaskPreset("Casual Shoes", [FieldPreset("Count", initialValue: Int16(2), upperBound: Int16(20))]),
        TaskPreset("Dress Pants", [FieldPreset("Count", initialValue: Int16(3), upperBound: Int16(20))]),
        TaskPreset("Dress Shirts", [FieldPreset("Count", initialValue: Int16(3), upperBound: Int16(20))]),
        TaskPreset("Jeans", [FieldPreset("Pair Count", unitsSuffix: "pr", initialValue: Int16(2), upperBound: Int16(20))]),
        TaskPreset("Shorts", [FieldPreset("Pair Count", unitsSuffix: "pr", initialValue: Int16(2), upperBound: Int16(20))]),
        TaskPreset("Sleep wear"),
        TaskPreset("Socks", [FieldPreset("Pair Count", unitsSuffix: "pr", initialValue: Int16(7), upperBound: Int16(20))]),
        TaskPreset("Sweatshirts", [FieldPreset("Count", initialValue: Int16(2), upperBound: Int16(20))]),
        TaskPreset("T-shirts", [FieldPreset("Count", initialValue: Int16(4), upperBound: Int16(20))]),
        TaskPreset("Underwear", [FieldPreset("Pair Count", unitsSuffix: "pr", initialValue: Int16(7), upperBound: Int16(20))]),
        TaskPreset("Workout wear"),
    ],
    .coldWeatherTravel: [
        TaskPreset("Cold Weather Socks"),
        TaskPreset("Gloves/Mittens"),
        TaskPreset("Hat"),
        TaskPreset("Jacket/Coat"),
        TaskPreset("Scarf/Neck Gaiter"),
        TaskPreset("Snow Boots"),
        TaskPreset("Snow Goggles"),
        TaskPreset("Snow Pants"),
        TaskPreset("Sweaters", [FieldPreset("Count", initialValue: Int16(2), upperBound: Int16(20))]),
    ],
    .warmWeatherTravel: [
        TaskPreset("Hat"),
        TaskPreset("Hiking Boots"),
        TaskPreset("Insect Repellent"),
        TaskPreset("Leisure Shoes"),
        TaskPreset("Sandals"),
        TaskPreset("Swimsuits"),
        TaskPreset("Umbrella"),
    ],
    .diveTravel: [
        TaskPreset("Buoyancy Compensator (BC)"),
        TaskPreset("Camera w/Charger"),
        TaskPreset("Dive Bag"),
        TaskPreset("Dive Computer", [FieldPreset("Battery Percent", unitsSuffix: "%", initialValue: Int16(100), stepValue: Int16(5), upperBound: Int16(100))]),
        TaskPreset("Dive Light, w/Charger"),
        TaskPreset("Dive Mask"),
        TaskPreset("Dry Bag"),
        TaskPreset("Ear Drops"),
        TaskPreset("Fins"),
        TaskPreset("Logbook"),
        TaskPreset("Mask Anti-Fog"),
        TaskPreset("Motion Sickness Pills"),
        TaskPreset("Octopus/Regulator"),
        TaskPreset("Padlock"),
        TaskPreset("Snorkel + Keeper"),
        TaskPreset("Wetsuit"),
        TaskPreset("Wetsuit Booties"),
    ],
    .businessTravel: [
        TaskPreset("Dress Socks", [FieldPreset("Pair Count", unitsSuffix: "pr", initialValue: Int16(3), upperBound: Int16(20))]),
        TaskPreset("Suits", [FieldPreset("Count", initialValue: Int16(2), upperBound: Int16(20))]),
        TaskPreset("Ties"),
        TaskPreset("Dress Shoes"),
    ],
    .autoInspection: [
        TaskPreset("Tires", [FieldPreset("Pressure", initialValue: false),
                             FieldPreset("Visual Inspection", initialValue: false)]),
        TaskPreset("Brake", [FieldPreset("Pad/Shoe Thickness", initialValue: false),
                             FieldPreset("Fluid Level", initialValue: false),
                             FieldPreset("Hose Inspection", initialValue: false),
                             FieldPreset("Parking Brake", initialValue: false)]),
        TaskPreset("Windshield", [FieldPreset("Wiper Check", initialValue: false),
                                  FieldPreset("Washer Fluid Level", initialValue: false)]),
    ],
    .iceAutoInspection: [
        TaskPreset("Electrical", [FieldPreset("Voltage Check", initialValue: false),
                                  FieldPreset("Lamp Check", initialValue: false)]),
        TaskPreset("Engine", [FieldPreset("Oil Level", initialValue: false),
                              FieldPreset("Hose Inspection", initialValue: false),
                              FieldPreset("Belt Inspection", initialValue: false),
                              FieldPreset("Air Filter", initialValue: false)]),
        TaskPreset("Radiator", [FieldPreset("Coolant Level", initialValue: false)]),
    ],
    .bikeInspection: [
        TaskPreset("Wheels/Tires", [FieldPreset("Pressure", initialValue: false),
                                    FieldPreset("Visual Inspection", initialValue: false)]),
        TaskPreset("Brake", [FieldPreset("Pad/Shoe Thickness", initialValue: false)]),
        TaskPreset("Drive Train", [FieldPreset("Derailleur Inspection", initialValue: false),
                                   FieldPreset("Gears Inspection", initialValue: false),
                                   FieldPreset("Chain Inspection", initialValue: false)]),
        TaskPreset("Derailleur", [FieldPreset("Inspection", initialValue: false)]),
        TaskPreset("Handlebars", [FieldPreset("Headset", initialValue: false),
                                  FieldPreset("Alignment", initialValue: false),
                                  FieldPreset("Inspection", initialValue: false)]),
        TaskPreset("Electrical", [FieldPreset("Lamp Check", initialValue: false)]),
    ],
    .ebikeInspection: [
        TaskPreset("Electrical", [FieldPreset("Voltage Check", initialValue: false)]),
    ],
]
